name: Checks

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci: 
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name : Run EC Validate (keyless)
      uses: ./
      with:
        image: ghcr.io/enterprise-contract/golden-container:latest
        identity: https:\/\/github\.com\/(slsa-framework\/slsa-github-generator|enterprise-contract\/golden-container)\/
        issuer: https://token.actions.githubusercontent.com

    - name : Run EC Validate (Long_Lived)
      uses: ./
      with:
        image: quay.io/redhat-appstudio/ec-golden-image:latest
        key: ${{ vars.PUBLIC_KEY }}
        policy: github.com/enterprise-contract/config//slsa3
        extra-params: --ignore-rekor